<!DOCTYPE html>
<html lang="br">
<head>
    <meta charset="utf-8">
    <title>Projeto POS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Le styles -->
    <link href="/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/bootstrap-theme.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/style.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Projeto Pós - OO</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">Inicio</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="http://projetoposoo.local/?page=onibus">Cadastrar</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="container">

    <div class="jumbotron">
        <h1>Projeto PHP - OO</h1>
        <p>Projeto desenvolvido para fins acadêmicos</p>
            <p><a class="btn btn-success btn-lg" href="https://github.com/kakashicafe/Projeto-Pos-2014" target="_blank">Baixar no GitHub &raquo;</a></p>
    </div>

    <div class="row">

        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Documentação</h3>
                </div>
                <div class="panel-body">
                    <p>Apartir do PHP 5, o modelo de objetos foi rescrito para permitir melhor performance e mais funcionalidades. Esta é uma grande modificação do PHP 4. PHP 5 tem um modelo de objetos completo.</p>
                    <p><a class="btn btn-success pull-right" href="http://php.net/manual/pt_BR/oop5.intro.php" target="_blank">Manual PHP OO &raquo;</a></p>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">GitHub</h3>
                </div>
                <div class="panel-body">
                    <p>GitHub é um Serviço de Web Hosting Compartilhado para projetos que usam o controle de versionamento Git. É escrito em Ruby on Rails pelos desenvolvedores da Logical Awesome (Chris Wanstrath, PJ Hyett e Tom Preston - Wernder). O GitHub possui planos comerciais e gratuitos para projetos de código aberto.</p>
                    <p><a class="btn btn-success pull-right" href="https://github.com/" target="_blank">Acessar o GitHub &raquo;</a></p>
                </div>
            </div>
        </div>

    </div>
    <hr>
    <footer>
        <p>&copy; 2014 by Grupo 2 pos Ltd. All rights reserved.</p>
    </footer>
</div> <!-- /container -->
</body>
</html>
</title>
</head>
<body>